
#include "hw_memmap.h"

#ifndef __DEMO_DRIVER__
    #include "eusci_a_uart.h"
    #include "gpio.h"
    #include "cs.h"
#else
    #include "lcd_c.h"
    #include "adc12_b.h"
    #include "aes256.h"
    #include "comp_e.h"
    #include "crc.h"
    #include "crc32.h"
    #include "cs.h"
    #include "dma.h"
    #include "esi.h"
    #include "eusci_a_spi.h"
    #include "eusci_a_uart.h"
    #include "eusci_b_i2c.h"
    #include "eusci_b_spi.h"
    #include "framctl.h"
    #include "gpio.h"
    #include "lcd_c.h"
    #include "mpu.h"
    #include "mpy32.h"
    #include "pmm.h"
    #include "ram.h"
    #include "ref_a.h"
    #include "rtc_b.h"
    #include "rtc_c.h"
    #include "sfr.h"
    #include "sysctl.h"
    #include "timer_a.h"
    #include "timer_b.h"
    #include "tlv.h"
    #include "wdt_a.h"
#endif

